#pragma once

#include <string>
#include <cstddef>  // Required for size_t in modern GCC
#include "engine/types.hpp"

/**
 * Maps a binary file generated by the translator into the process's 
 * virtual memory space.
 * * @param filepath Path to the .bin file
 * @param out_num_ticks Reference to store the count of OrderBookState objects found
 * @return A constant pointer to the start of the memory-mapped array
 */
const OrderBookState* load_binary_data(const std::string& filepath, size_t& out_num_ticks);